services:
  - type: web
    name: tvr-hitech-lab-service-desk
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 20
